name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install Dependencies
      run: npm install || echo "No dependencies"

    - name: Run Tests
      run: npm test || echo "Tests skipped"

    - name: Build Docker Image
      run: docker build -t photostudio-app .

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.venkataramana773

 }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Push Image
      run: |
        docker tag photostudio-app ${{ secrets.DOCKERHUB_USERNAME }}/photostudio-app:latest
        docker push ${{ secrets.DOCKERHUB_USERNAME }}/photostudio-app:latest